const mongoose = require("mongoose");

/**
 * A directed task to move received stock from the receiving pool into a
 * storage bin. Generated by postGRN() for each accepted line; completed by a
 * warehouse operator (scan lot → scan/select destination bin), which calls
 * locationService.moveBinStock(pool → bin) and writes the InventoryBin row.
 */
const putawayTaskSchema = new mongoose.Schema(
  {
    companyId: { type: mongoose.Schema.Types.ObjectId, ref: "Company", required: true },
    warehouseId: { type: mongoose.Schema.Types.ObjectId, ref: "Warehouse", required: true },
    grnId: { type: mongoose.Schema.Types.ObjectId, ref: "GRN" },
    lineIndex: { type: Number },

    inventoryId: { type: mongoose.Schema.Types.ObjectId, ref: "Inventory", required: true },
    productId: { type: mongoose.Schema.Types.ObjectId, ref: "Product" },
    qty: { type: Number, required: true },

    suggestedLocationId: { type: mongoose.Schema.Types.ObjectId, ref: "Location", default: null },
    actualLocationId: { type: mongoose.Schema.Types.ObjectId, ref: "Location", default: null },

    status: { type: String, enum: ["pending", "in_progress", "completed", "cancelled"], default: "pending" },
    assignedTo: { type: mongoose.Schema.Types.ObjectId },
    completedAt: { type: Date },
  },
  { timestamps: true }
);

putawayTaskSchema.index({ companyId: 1, status: 1, createdAt: 1 });
putawayTaskSchema.index({ warehouseId: 1, status: 1 });

module.exports = mongoose.model("PutawayTask", putawayTaskSchema);
