// FAQ content for the Company and Seller portals. Pure data (no JSX) so the same
// shared <FaqView /> can render either set, and the copy stays easy to edit in
// one place. Grouped by category; each item is { q, a }.

export const COMPANY_FAQ = [
  {
    category: 'Registration & Onboarding',
    icon: 'how_to_reg',
    items: [
      { q: 'Khetify par company account kaise banaye?', a: 'Home page par "Register as Company" par click karke form bharein — company name, email, phone aur password dekar account create ho jata hai.' },
      { q: 'Company register karne ke liye kya documents chahiye?', a: 'Business name, GST number, trade license, contact details aur bank/PAN details onboarding steps me maange jaate hain.' },
      { q: 'Registration free hai kya?', a: 'Account banana free hai. Kuch premium features subscription plan par depend karte hain (Billing section dekhein).' },
      { q: 'Ek email se kitne company accounts ban sakte hain?', a: 'Ek email par ek hi company account allowed hai. Alag company ke liye alag email use karein.' },
      { q: 'Registration ke baad kya hota hai?', a: 'Aapka application review ke liye jata hai. Approve hone par aap dashboard access kar paate hain.' },
      { q: 'Approval me kitna time lagta hai?', a: 'Aam taur par 24 ghante ke andar setup complete ho jata hai; verification me thoda extra time lag sakta hai.' },
      { q: 'Meri registration reject kyun hui?', a: 'Galat/incomplete documents, invalid GST ya duplicate company hone par reject ho sakti hai. Support se reason confirm karein.' },
      { q: 'Setup adhura chhod diya to data save rahega?', a: 'Haan, aap wahi se continue kar sakte hain jahan chhoda tha.' },
      { q: 'Kya Khetify khud logistics/payment handle karta hai?', a: 'Nahi. Khetify platform infrastructure, pricing visibility aur network access deta hai. Delivery aur payment companies/sellers khud manage karte hain.' },
      { q: 'Onboarding me help chahiye to kise contact karein?', a: 'support@khetify.com par mail karein — team setup me madad karti hai.' },
    ],
  },
  {
    category: 'Account, Login & Security',
    icon: 'lock',
    items: [
      { q: 'Company login kaise karun?', a: 'Company Login page par registered email aur password se login karein.' },
      { q: 'Password bhool gaya, kya karun?', a: '"Forgot Password" par click karein → email par reset link aayega → naya password set karein.' },
      { q: 'Password reset link kitni der valid rehta hai?', a: 'Security ke liye link limited time baad expire ho jata hai; expire hone par dobara request karein.' },
      { q: 'Password change kaha se hota hai?', a: 'Login karke Settings me jaakar password update kar sakte hain.' },
      { q: 'Mera account secure kaise rehta hai?', a: 'Enterprise-grade encryption aur role-based access control se aapka data protected rehta hai.' },
      { q: 'Login nahi ho raha, kya karun?', a: 'Email/password check karein, password reset try karein; phir bhi issue ho to support ticket raise karein.' },
      { q: 'Account temporarily lock kyun hua?', a: 'Kai baar galat password ya security reasons se account lock ho sakta hai — support se unlock karwayein.' },
    ],
  },
  {
    category: 'Dashboard & Navigation',
    icon: 'dashboard',
    items: [
      { q: 'Dashboard par kya-kya dikhta hai?', a: 'Sales, orders, inventory levels, returns aur payments ka real-time overview.' },
      { q: 'Notifications kaha milti hain?', a: 'Notifications section me orders, approvals, stock alerts aur system updates aate hain.' },
      { q: 'Main modules kaun se hain?', a: 'Inventory (IMS), Product Catalog, Orders, Returns, Sellers, Supply Requests, Billing, Users aur Support.' },
      { q: 'Dashboard data kitni jaldi update hota hai?', a: 'Real-time — stock, orders aur payments turant reflect hote hain.' },
      { q: 'Mobile par bhi portal chalta hai?', a: 'Haan, portal responsive hai — mobile aur desktop dono par kaam karta hai.' },
    ],
  },
  {
    category: 'Product Upload & Catalog',
    icon: 'inventory_2',
    items: [
      { q: 'Product kaise upload karun?', a: 'Upload Product page se name, category, price, images aur stock details bharkar add karein.' },
      { q: 'Bulk me products upload ho sakte hain?', a: 'Haan, bulk upload tools se poori inventory ek saath digitize kar sakte hain.' },
      { q: 'Product edit kaise karun?', a: 'Product Catalog me product select karke Edit Product page se details update karein.' },
      { q: 'Product image ka format kya hona chahiye?', a: 'Standard image formats (JPG/PNG) supported hain; clear product photos recommend kiye jaate hain.' },
      { q: 'Product delete/deactivate kaise karun?', a: 'Catalog me product ke options se use deactivate ya remove kar sakte hain.' },
      { q: 'Product ka price baad me change kar sakta hoon?', a: 'Haan, Edit Product se price kabhi bhi update ho jata hai.' },
      { q: 'Bulk upload fail ho raha hai, kya karun?', a: 'File format/columns check karein; issue rahe to Support (Product Upload) me ticket banayein.' },
      { q: 'Ek product ke multiple variants add ho sakte hain?', a: 'Haan, size/quantity/packaging ke hisaab se variants add kiye ja sakte hain.' },
      { q: 'Out-of-stock product catalog me dikhega?', a: 'Stock 0 hone par product out-of-stock mark ho jata hai; aap use hide ya restock kar sakte hain.' },
    ],
  },
  {
    category: 'Inventory Management (IMS)',
    icon: 'warehouse',
    items: [
      { q: 'IMS kya hai?', a: 'Intelligent Inventory Management — multiple warehouses me real-time stock tracking, auto-reorder aur expiry management.' },
      { q: 'Stock levels kaise track hote hain?', a: 'availableStock = online + offline − reserved; har stock change ledger me record hota hai.' },
      { q: 'Ek se zyada warehouse ka stock sync hota hai?', a: 'Haan, multi-warehouse syncing se sabhi locations ka stock ek jagah dikhta hai.' },
      { q: 'Batch aur expiry management hai?', a: 'Haan, batch number aur expiry date ke saath stock control hota hai.' },
      { q: 'Expiry ke pehle alert milta hai?', a: 'Haan, expiry近 aane par system alert deta hai taaki wastage kam ho.' },
      { q: 'Stock adjustment kaise karun?', a: 'IMS me manual adjustment option se stock badha/ghata sakte hain — har change log hota hai.' },
      { q: 'Inbound (GRN) kaise record karta hoon?', a: 'Operations me goods receive karke GRN post karein — stock automatically update hota hai.' },
      { q: 'Stock movement history dekh sakta hoon?', a: 'Haan, har stock change ka append-only ledger maintain hota hai jise delete nahi kiya ja sakta.' },
      { q: 'Inventory galat dikh raha hai to?', a: 'Movements ledger check karein; discrepancy ho to Support (Inventory & Stock) me report karein.' },
    ],
  },
  {
    category: 'Warehouses & Operations',
    icon: 'local_shipping',
    items: [
      { q: 'Warehouse kaise add karun?', a: 'Warehouses section me naam, location aur capacity dekar naya warehouse add karein.' },
      { q: 'Ek warehouse se dusre me stock transfer ho sakta hai?', a: 'Haan, inter-warehouse transfer supported hai aur transaction-safe tareeke se record hota hai.' },
      { q: 'Warehouse-wise stock report milti hai?', a: 'Haan, har warehouse ka alag stock aur movement view available hai.' },
      { q: 'Operations section me kya hota hai?', a: 'Inbound, outbound, transfers aur day-to-day warehouse activities manage hoti hain.' },
      { q: 'Labels/barcodes generate ho sakte hain?', a: 'Haan, Labels section se product/lot labels generate kiye ja sakte hain.' },
    ],
  },
  {
    category: 'Orders & Returns',
    icon: 'receipt_long',
    items: [
      { q: 'Orders kaha dikhte hain?', a: 'Orders page par saare incoming orders status ke saath dikhte hain.' },
      { q: 'Order kaise process karun?', a: 'Order accept karke pack/dispatch update karein; stock automatically adjust hota hai.' },
      { q: 'Order history kaha milti hai?', a: 'Order History page par purane orders search aur filter kar sakte hain.' },
      { q: 'Invoice automatically banta hai?', a: 'Haan, GST-compliant invoicing automated hoti hai.' },
      { q: 'Order cancel ho to stock wapas aata hai?', a: 'Haan, cancellation par reserved stock release ho jata hai.' },
      { q: 'Delivery Khetify karta hai kya?', a: 'Nahi, delivery company khud arrange karti hai — platform sirf order visibility deta hai.' },
      { q: 'Returns kaise handle hote hain?', a: 'Returns page par return requests aati hain jinhe aap approve/reject kar sakte hain.' },
      { q: 'Return approve karne par stock update hota hai?', a: 'Haan, accepted return ka stock wapas inventory me add ho jata hai.' },
    ],
  },
  {
    category: 'Sellers, Dealers & PC Applications',
    icon: 'groups',
    items: [
      { q: 'Sellers/dealers kaise add karun?', a: 'Sellers section me dealer profile create/invite karke add karein.' },
      { q: 'PC Applications kya hoti hain?', a: 'Sellers aapke products bechne ke liye Principal Certificate (PC) apply karte hain; aap unhe review karke certificate issue karte hain.' },
      { q: 'Seller ki application kaise review karun?', a: 'PC Applications page par row kholkar business details, documents verify karein, phir approve/reject/issue karein.' },
      { q: 'Application form customize kar sakta hoon?', a: 'Haan, PC Applications me form builder se fields (label, type, required, profile auto-fill) set kar sakte hain.' },
      { q: 'Credit limit set kar sakta hoon?', a: 'Haan, har dealer ke liye credit limit controls set kiye ja sakte hain.' },
      { q: 'Dealer performance track hoti hai?', a: 'Haan, performance ratings aur order history ek unified profile me dikhti hai.' },
      { q: 'Certificate revoke kar sakta hoon?', a: 'Haan, issued certificate ko reason ke saath revoke aur baad me reinstate kiya ja sakta hai.' },
      { q: 'Supply request kya hai?', a: 'Sellers ki taraf se stock/supply ki demand jise company Supply Requests page se fulfil karti hai.' },
    ],
  },
  {
    category: 'Billing, Users & Support',
    icon: 'payments',
    items: [
      { q: 'Billing details kaha milti hain?', a: 'Billing page par current plan, invoices aur payment status dikhta hai.' },
      { q: 'Plan upgrade/downgrade kaise karun?', a: 'Billing section se plan change kar sakte hain.' },
      { q: 'Premium feature locked kyun dikh raha hai?', a: 'Wo feature aapke current plan me nahi hai — upgrade karne par unlock ho jayega.' },
      { q: 'Invoice download kar sakta hoon?', a: 'Haan, Billing me har invoice download available hai.' },
      { q: 'Team members ko roles kaise dete hain?', a: 'Users section me member add karke role assign karein (admin, staff, auditor read-only, etc.).' },
      { q: 'Koi issue ho to help kaise milegi?', a: 'Support Center me "Create Support Request" se ticket raise karein — team aam taur par 4 ghante me reply karti hai. Email: support@khetify.com (Mon–Sat, 9 AM–6 PM).' },
    ],
  },
];

export const SELLER_FAQ = [
  {
    category: 'Registration & Onboarding',
    icon: 'how_to_reg',
    items: [
      { q: 'Khetify par seller kaise ban sakta hoon?', a: 'Seller page par "Register as Seller" par click karke form bharein — naam, email, phone aur password dekar account create ho jata hai.' },
      { q: 'Seller register karne ke liye kya chahiye?', a: 'Shop/business name, contact details, address, GST/license (agar ho) aur bank/PAN details onboarding steps me maange jaate hain.' },
      { q: 'Seller banna free hai kya?', a: 'Account banana free hai; kuch advanced features plan/authorization par depend karte hain.' },
      { q: 'Registration ke baad kya karna hota hai?', a: 'Onboarding complete karein → profile bharein → jis company ka product bechna hai uske liye Principal Certificate (PC) apply karein.' },
      { q: 'Onboarding adhura chhoda to data save rahega?', a: 'Haan, aap wahi se continue kar sakte hain jahan chhoda tha.' },
      { q: 'Account turant chalu ho jata hai?', a: 'Account ban jata hai, par kisi company ke products bechne ke liye us company se PC issue hona zaroori hai.' },
    ],
  },
  {
    category: 'Login, Account & Security',
    icon: 'lock',
    items: [
      { q: 'Seller login kaise karun?', a: 'Seller Login page par registered email aur password se login karein.' },
      { q: 'Password bhool gaya to?', a: '"Forgot Password" par jaakar email par reset link mangwayein aur naya password set karein.' },
      { q: 'Password change kaha se hota hai?', a: 'Login karke Settings/Profile me jaakar password update karein.' },
      { q: 'Mera data secure hai?', a: 'Haan, encryption aur role-based access control se aapka account aur data protected rehta hai.' },
      { q: 'Login nahi ho raha, kya karun?', a: 'Email/password verify karein, reset try karein; phir bhi na chale to support se contact karein.' },
      { q: 'Ek se zyada log account use kar sakte hain?', a: 'Haan, Team section me members ko roles ke saath add kar sakte hain.' },
    ],
  },
  {
    category: 'Companies & Principal Certificate (PC)',
    icon: 'verified',
    items: [
      { q: 'Principal Certificate (PC) kya hota hai?', a: 'PC wo authorization hai jo ek company aapko deti hai taaki aap uske products officially bech sakein.' },
      { q: 'PC ke liye kaise apply karun?', a: 'Companies section me company search karke "Apply for PC" par click karein aur application form bharein.' },
      { q: 'Company kaise dhoondhun?', a: 'Companies page ke search box me company ka naam ya region daalein.' },
      { q: 'Recommended companies kya hoti hain?', a: 'Aapke profile/region ke hisaab se suggest ki gayi companies jinke liye aap PC apply kar sakte hain.' },
      { q: 'PC application ka status kaise pata chalega?', a: 'Companies/Certifications page par status dikhta hai — In progress, PC issued (active) ya Rejected.' },
      { q: '"PC issued" ka matlab kya hai?', a: 'Company ne aapko authorize kar diya — ab aap uske products bech sakte hain.' },
      { q: 'Meri PC application reject kyun hui?', a: 'Incomplete details, eligibility ya company ki policy ke hisaab se reject ho sakti hai; dobara apply kar sakte hain.' },
      { q: 'Ek saath kitni companies ke liye PC le sakta hoon?', a: 'Aap multiple companies ke liye apply/PC hold kar sakte hain.' },
      { q: 'Bina PC ke company ke products bech sakta hoon?', a: 'Nahi, kisi company ke products bechne ke liye us company ka PC hona zaroori hai.' },
      { q: 'Certifications page par kya hota hai?', a: 'Yahan aapki PC applications aur company-specific certification forms manage hote hain.' },
    ],
  },
  {
    category: 'Dashboard & Hub',
    icon: 'dashboard',
    items: [
      { q: 'Seller dashboard par kya dikhta hai?', a: 'Sales, orders, inventory, active companies (PC) aur performance ka overview.' },
      { q: 'Administration section me kya hota hai?', a: 'Team, Certifications, Billing, Customers aur Companies jaise account-level sections.' },
      { q: 'Data kitni jaldi update hota hai?', a: 'Real-time — orders aur stock changes turant reflect hote hain.' },
      { q: 'Mobile par bhi seller portal chalta hai?', a: 'Haan, portal responsive hai — mobile aur desktop dono par kaam karta hai.' },
    ],
  },
  {
    category: 'Product Catalog & Inventory',
    icon: 'inventory_2',
    items: [
      { q: 'Seller product catalog me kya hota hai?', a: 'Jin companies ka PC aapke paas hai, unke products aap catalog me manage/sell kar sakte hain.' },
      { q: 'Product apne aap add hote hain?', a: 'Company ke authorized products aapke liye available ho jaate hain; aap unhe apne stock ke saath manage karte hain.' },
      { q: 'Marketplace listings kya hain?', a: 'Wo products jo aapne Khetify storefront par publish kiye hain.' },
      { q: 'Seller inventory kaise manage hoti hai?', a: 'Inventory section me aapke products ka stock, batch aur availability track hoti hai.' },
      { q: 'Available stock kaise calculate hota hai?', a: 'availableStock = online + offline − reserved; sale/reservation par automatically adjust hota hai.' },
      { q: 'Batch aur expiry track hoti hai?', a: 'Haan, batch number aur expiry date ke saath stock control kar sakte hain.' },
      { q: 'Low-stock alert milega?', a: 'Haan, stock minimum level se neeche jaane par alert milta hai.' },
      { q: 'Stock movement history dekh sakta hoon?', a: 'Haan, har stock change ka append-only ledger maintain hota hai.' },
    ],
  },
  {
    category: 'Warehouses & Operations',
    icon: 'local_shipping',
    items: [
      { q: 'Warehouse kaise add karun?', a: 'Warehouses section me naam, location aur capacity dekar warehouse add karein.' },
      { q: 'Multiple warehouses rakh sakta hoon?', a: 'Haan, ek se zyada storage locations add kiye ja sakte hain.' },
      { q: 'Warehouse ke beech stock transfer ho sakta hai?', a: 'Haan, inter-warehouse transfer supported hai aur safely record hota hai.' },
      { q: 'Operations section me kya hota hai?', a: 'Inbound, outbound, transfers aur trace jaisi day-to-day stock activities.' },
      { q: 'Labels/barcodes print ho sakte hain?', a: 'Haan, Labels section se product/lot ke barcodes generate aur print kar sakte hain.' },
    ],
  },
  {
    category: 'Outbound, Supply & Customers',
    icon: 'local_mall',
    items: [
      { q: 'Outbound kya hota hai?', a: 'Outbound section me aap customers/dealers ko products dispatch/sell karte hain.' },
      { q: 'Order cancel ho to stock wapas aata hai?', a: 'Haan, cancellation par reserved stock release ho jata hai.' },
      { q: 'Delivery Khetify karta hai kya?', a: 'Nahi, delivery aap khud arrange karte hain — platform sirf order visibility deta hai.' },
      { q: 'Supply request kya hai?', a: 'Jab aapko company se stock chahiye, aap Supply section se replenishment request bhejte hain.' },
      { q: 'Supply request ka status kaise dekhun?', a: 'Supply page par request pending/approved/fulfilled status ke saath dikhti hai.' },
      { q: 'Customers section me kya hota hai?', a: 'Aapke buyers/farmers/dealers ki details, order history aur relationship management.' },
      { q: 'Customer ka credit/outstanding track hota hai?', a: 'Haan, customer-wise dues aur credit details manage kar sakte hain.' },
    ],
  },
  {
    category: 'Team, Analytics, Billing & Support',
    icon: 'payments',
    items: [
      { q: 'Team members kaise add karun?', a: 'Team section me member add karke role assign karein (admin/manager/staff).' },
      { q: 'Role-based access hai kya?', a: 'Haan, alag members ko alag permissions (jaise staff, auditor read-only) di ja sakti hain.' },
      { q: 'Analytics me kya milta hai?', a: 'Sales trends, top products, stock aging, expiry aur movement reports.' },
      { q: 'Billing me kya hota hai?', a: 'Aapka subscription plan aur usage; plan switch admin-only hota hai.' },
      { q: 'Khetify ki responsibility kya hai?', a: 'Khetify platform infrastructure, pricing visibility aur network access deta hai — delivery aur payment aap khud manage karte hain.' },
      { q: 'Koi issue ho to help kaise milegi?', a: 'Portal ke Support/Help option se request raise karein ya support par contact karein — issue detail ke saath likhein taaki jaldi solve ho.' },
    ],
  },
];
