// FAQ content for the Company and Seller portals. Pure data (no JSX) so the same
// shared <FaqView /> can render either set, and the copy stays easy to edit in
// one place. Grouped by category; each item is { q, a }.

export const COMPANY_FAQ = [
  {
    category: 'Registration & Onboarding',
    icon: 'how_to_reg',
    items: [
      { q: 'How do I create a company account on Khetify?', a: 'Click the "Register as Company" button on the home page and complete the registration form by providing your company name, email address, phone number, and password. Once submitted, your company account will be created.' },
      { q: 'What documents are required to register a company?', a: 'During the onboarding process, you will be asked to provide your business name, GST number, trade license, contact information, and bank/PAN details for verification.' },
      { q: 'Is company registration free?', a: 'Yes, creating a company account is completely free. However, some advanced features are available only with a premium subscription plan. Please refer to the Billing section for more information.' },
      { q: 'How many company accounts can be created using one email address?', a: 'Only one company account can be registered with a single email address. If you need to register another company, you must use a different email address.' },
      { q: 'What happens after I complete the registration?', a: 'Your application will be submitted for review. Once it is approved, you will receive access to the Company Dashboard and all available company features.' },
      { q: 'How long does the approval process take?', a: 'In most cases, the approval process is completed within 24 hours. However, additional verification may require extra processing time.' },
      { q: 'Why was my registration application rejected?', a: 'Your application may be rejected due to incomplete or incorrect information, an invalid GST number, duplicate company registration, or missing verification documents. Please contact the support team for the exact reason and further assistance.' },
      { q: 'What are the steps involved in the registration process?', a: 'The registration process consists of: 1) Enter basic company information. 2) Complete the company setup (Steps 2–5). 3) Upload the required documents. 4) Submit your application. 5) Wait for approval. Your progress is automatically saved at each step.' },
      { q: 'Will my information be saved if I leave the setup before completing it?', a: 'Yes. Your progress is automatically saved, allowing you to resume the registration process from where you left off.' },
      { q: 'Can I edit my registration details after submitting the application?', a: 'Some information can be updated before your application is approved. Once approved, changes to certain details may require submitting a support request.' },
      { q: 'Does Khetify handle logistics and payments?', a: 'No. Khetify provides the platform infrastructure, product visibility, and business network. Delivery, logistics, and payment transactions are managed directly between the company and the seller.' },
      { q: 'Who should I contact if I need help during onboarding?', a: 'If you need assistance during the onboarding process, please contact our support team at support@khetify.com. Our team typically responds within 24 hours and will help you complete your storefront setup.' },
    ],
  },
  {
    category: 'Company Setup & Approval',
    icon: 'business',
    items: [
      { q: 'What information should be configured in the company profile?', a: 'Your company profile should include company information, logo, registered address, GST/license details, warehouse information, and bank details.' },
      { q: 'What should I do after seeing the "Submission Complete" message?', a: 'Once your application has been submitted successfully, simply wait for the approval process to be completed. After approval, you will receive a confirmation notification and your Company Dashboard will be activated.' },
      { q: 'How can I check my application approval status?', a: 'Log in to your company account to view your application status. The status will be displayed as Pending, Approved, or Rejected.' },
      { q: 'Can I update my company details after approval?', a: 'Yes. General company information can be updated from the Company Settings page. However, changes to legal information such as the company name or GST details require assistance from the support team.' },
      { q: 'Can I update my company setup later?', a: 'Yes. Most company information can be updated at any time from the Company Information or Settings page.' },
      { q: 'Can I add multiple branches or warehouse locations?', a: 'Yes. Khetify allows you to add and manage multiple warehouses or branch locations through the Warehouses section.' },
      { q: 'How do I update my company logo and branding?', a: 'You can upload a new company logo and update your branding information from the Company Profile or Settings page.' },
      { q: 'What should I do if I entered incorrect information during the setup process?', a: 'If your application has not yet been approved, you can return to the relevant step and update the information. After approval, you will need to submit a support request under the Account & Settings category to request any necessary changes.' },
    ],
  },
  {
    category: 'Account, Login & Security',
    icon: 'lock',
    items: [
      { q: 'How do I log in to my company account?', a: 'Go to the Company Login page and sign in using your registered email address and password.' },
      { q: 'What should I do if I forget my password?', a: 'Click "Forgot Password", enter your registered email address, and follow the password reset link sent to your inbox to create a new password.' },
      { q: 'How long is the password reset link valid?', a: 'For security reasons, the password reset link is valid only for a limited period. If the link expires, you will need to request a new one.' },
      { q: 'How can I change my password?', a: 'After logging in, navigate to Settings and update your password from the Account Security section.' },
      { q: 'How is my company account secured?', a: 'Your account is protected using enterprise-grade encryption, secure authentication, and role-based access control to help safeguard your data.' },
      { q: 'Can multiple users access the same company account?', a: 'Yes. You can add multiple team members from the Users/Team section and assign appropriate roles and permissions based on their responsibilities.' },
      { q: 'I am unable to log in. What should I do?', a: 'First, verify that you are using the correct email address and password. If the issue persists, try resetting your password. If you still cannot access your account, please submit a support request for assistance.' },
      { q: 'Why has my account been temporarily locked?', a: 'Your account may be temporarily locked due to multiple unsuccessful login attempts or security-related reasons. Please contact the support team to have your account unlocked.' },
    ],
  },
  {
    category: 'Dashboard & Navigation',
    icon: 'dashboard',
    items: [
      { q: 'What information is available on the dashboard?', a: 'The dashboard provides a real-time overview of your sales, orders, inventory levels, returns, payments, and other key business metrics.' },
      { q: 'Where can I find notifications?', a: 'You can view notifications in the Notifications section, where you will receive updates about orders, approvals, inventory alerts, and important system announcements.' },
      { q: 'What are the main modules available in the Company Portal?', a: 'The Company Portal includes: Inventory Management System (IMS), Product Catalog, Orders, Returns, Sellers, Supply Requests, Billing, Users, and Support.' },
      { q: 'How frequently is the dashboard updated?', a: 'The dashboard is updated in real time, ensuring that changes to inventory, orders, and payments are reflected immediately.' },
      { q: 'Can I access the Company Portal on a mobile device?', a: 'Yes. The Company Portal is fully responsive and can be accessed from both desktop and mobile devices.' },
    ],
  },
  {
    category: 'Product Upload & Catalog',
    icon: 'inventory_2',
    items: [
      { q: 'How do I upload a product?', a: 'Go to the Upload Product page and enter the product name, category, pricing, images, and inventory details. Once all required information is provided, submit the product to add it to your catalog.' },
      { q: 'Can I upload multiple products in bulk?', a: 'Yes. Khetify supports bulk product uploads, allowing you to upload and manage your entire inventory efficiently using the bulk import feature.' },
      { q: 'How can I edit an existing product?', a: 'Navigate to the Product Catalog, select the product you want to modify, and click Edit Product to update its details.' },
      { q: 'What image formats are supported for product uploads?', a: 'Khetify supports standard image formats such as JPG and PNG. For the best customer experience, use high-quality, clear product images.' },
      { q: 'How do I delete or deactivate a product?', a: 'Open the product from the Product Catalog and use the available options to either deactivate or permanently remove it from your catalog.' },
      { q: 'Can I update the product price later?', a: 'Yes. Product pricing can be updated at any time through the Edit Product page.' },
      { q: 'What product categories are available?', a: 'Khetify supports a wide range of agricultural product categories, including seeds, fertilizers, irrigation equipment, farming tools, crop protection products, and more. Select the category that best matches your product.' },
      { q: 'My bulk product upload failed. What should I do?', a: 'Verify that your upload file follows the required format and contains the correct column structure. If the issue persists, submit a support request under the Product Upload category.' },
      { q: 'Are products reviewed before they are published?', a: "Yes. In certain cases, products may undergo a review process to ensure they comply with Khetify's product listing guidelines before becoming publicly available." },
      { q: 'Can I add multiple variants for a single product?', a: 'Yes. You can create multiple product variants based on attributes such as size, quantity, packaging type, or other applicable options.' },
      { q: 'Where can I find the product upload guidelines?', a: 'Detailed product upload guidelines are available in the Support Center under the Product Upload Guidelines section.' },
      { q: 'Will out-of-stock products still appear in the catalog?', a: "When a product's inventory reaches zero, it is automatically marked as Out of Stock. You can choose to hide the product or restock it to make it available again." },
    ],
  },
  {
    category: 'Inventory Management (IMS)',
    icon: 'warehouse',
    items: [
      { q: 'What is IMS?', a: "IMS (Intelligent Inventory Management System) is Khetify's inventory management solution that provides real-time stock tracking across multiple warehouses, automated reorder management, and batch and expiry tracking." },
      { q: 'How are inventory levels calculated?', a: 'Available Stock = Online Stock + Offline Stock − Reserved Stock. Every inventory transaction is recorded in a secure audit ledger for complete traceability.' },
      { q: 'Can inventory be synchronized across multiple warehouses?', a: 'Yes. Khetify automatically synchronizes inventory across all connected warehouses, providing a unified view of stock availability.' },
      { q: 'Does Khetify support batch and expiry management?', a: 'Yes. Products can be managed using batch numbers and expiry dates, enabling accurate inventory tracking and compliance.' },
      { q: 'Will I receive alerts before products expire?', a: 'Yes. Khetify sends automated notifications before products reach their expiry date, helping you minimize waste and manage inventory more effectively.' },
      { q: 'How does automatic reordering work?', a: 'When inventory falls below the predefined minimum stock level, the system can automatically trigger a reorder based on your inventory settings.' },
      { q: 'How can I adjust inventory manually?', a: 'You can manually increase or decrease inventory through the IMS module. Every adjustment is recorded in the audit log to maintain complete inventory history.' },
      { q: 'What are lots?', a: 'A lot represents a specific production batch or consignment of products. Lots enable complete tracking and traceability throughout the product lifecycle.' },
      { q: 'How do I record inbound inventory (GRN)?', a: 'Receive incoming goods through the Inbound section and create a Goods Receipt Note (GRN). Once the GRN is posted, inventory levels are updated automatically.' },
      { q: 'How is outbound inventory managed?', a: 'Use the Outbound section to record product dispatches. The system automatically reserves and deducts inventory based on the dispatched quantities.' },
      { q: 'Can I view my inventory movement history?', a: 'Yes. Khetify maintains an append-only inventory ledger that records every stock movement. These records provide a complete audit trail and cannot be deleted.' },
      { q: 'What should I do if my inventory appears incorrect?', a: 'Review your inventory movement ledger to identify any discrepancies. If the issue cannot be resolved, submit a support request under the Inventory & Stock category for further assistance.' },
    ],
  },
  {
    category: 'Warehouses & Operations',
    icon: 'local_shipping',
    items: [
      { q: 'How do I add a new warehouse?', a: 'Navigate to the Warehouses section and enter the warehouse name, location, and storage capacity. Once the required information is provided, save the details to add the warehouse.' },
      { q: 'Can I transfer inventory between warehouses?', a: 'Yes. Khetify supports secure inter-warehouse inventory transfers. Every transfer is recorded automatically to maintain an accurate inventory history.' },
      { q: 'Can I view warehouse-specific inventory reports?', a: 'Yes. You can access detailed inventory and stock movement reports for each warehouse individually.' },
      { q: 'What can I manage in the Operations section?', a: 'The Operations module allows you to manage inbound shipments, outbound dispatches, warehouse transfers, and other day-to-day warehouse activities.' },
      { q: 'Can I monitor warehouse capacity?', a: 'Yes. Khetify enables you to track both the total warehouse capacity and current occupancy to help optimize storage utilization.' },
      { q: 'Can I generate labels and barcodes?', a: 'Yes. Product labels and lot barcodes can be generated from the Labels section for inventory identification and traceability.' },
    ],
  },
  {
    category: 'Orders',
    icon: 'receipt_long',
    items: [
      { q: 'Where can I view my orders?', a: 'All incoming orders can be viewed on the Company Orders page, along with their current processing status.' },
      { q: 'What order statuses are available?', a: 'Orders can have the following statuses: New, Processing, Dispatched, Delivered, and Cancelled.' },
      { q: 'How do I process an order?', a: 'Open the order, review the details, accept it, and update the packing and dispatch information. The inventory is automatically adjusted based on the order.' },
      { q: 'Where can I view my order history?', a: 'You can access previous orders from the Order History page, where orders can be searched, filtered, and reviewed.' },
      { q: 'Are invoices generated automatically?', a: 'Yes. Khetify automatically generates GST-compliant invoices for eligible orders.' },
      { q: 'What happens to inventory if an order is cancelled?', a: 'When an order is cancelled, the reserved inventory is automatically released and added back to the available stock.' },
      { q: 'Does Khetify handle product delivery?', a: 'No. Khetify provides the platform for order management and visibility. Delivery and logistics are managed directly by the company or its logistics partner.' },
      { q: 'How are payments collected?', a: 'Payments are settled directly between the company and the seller. Khetify does not process or manage payment transactions.' },
    ],
  },
  {
    category: 'Returns',
    icon: 'assignment_return',
    items: [
      { q: 'How are product returns managed?', a: 'Return requests are available on the Company Returns page, where you can review each request and either approve or reject it based on your return policy.' },
      { q: 'Is inventory updated after a return is approved?', a: 'Yes. Once a return request is approved, the returned items are automatically added back to your available inventory.' },
      { q: 'Is there a time limit for product returns?', a: "Yes. The return window is determined by your company's return policy and the agreed terms with the seller." },
      { q: 'Can I reject a return request?', a: 'Yes. You may reject a return request if it does not comply with your return policy. It is recommended to provide a reason for the rejection.' },
      { q: 'Where can I find the return and issue handling guidelines?', a: 'Detailed return policies and issue handling procedures are available in the Support Center under the Returns & Issue Handling section.' },
    ],
  },
  {
    category: 'Sellers / Dealers (CRM)',
    icon: 'groups',
    items: [
      { q: 'How do I add sellers or dealers?', a: 'Go to the Company Sellers section to create a new dealer profile or invite sellers to join your business network.' },
      { q: 'How can I manage seller applications?', a: 'Seller applications can be reviewed from the Supply Requests or PC Applications section, where you can approve or reject each request.' },
      { q: 'Can I set a credit limit for dealers?', a: 'Yes. You can configure individual credit limits for each dealer based on your business requirements.' },
      { q: 'Can I monitor dealer performance?', a: 'Yes. Each dealer profile includes performance metrics, order history, and other relevant information to help you evaluate their performance.' },
      { q: 'Can I block or deactivate a seller?', a: 'Yes. Sellers who fail to comply with your business policies can be blocked or deactivated from the Sellers section.' },
      { q: 'Can I view all orders placed by a dealer?', a: 'Yes. Each dealer profile contains a complete order history, making it easy to review previous transactions.' },
      { q: 'How can I connect with new sellers?', a: 'Khetify provides access to a pre-verified network of sellers, helping you discover and connect with reliable business partners.' },
      { q: 'How are seller ratings determined?', a: 'Seller ratings are calculated based on factors such as order fulfillment performance, delivery timeliness, and overall transaction history.' },
    ],
  },
  {
    category: 'Supply Requests & Transport',
    icon: 'sync_alt',
    items: [
      { q: 'What is a supply request?', a: 'A supply request is a request submitted by a seller for product inventory. Companies can review and fulfill these requests based on product availability.' },
      { q: 'How do I approve a supply request?', a: 'Navigate to the Supply Requests section, open the request, review its details, and choose to Accept or Decline it.' },
      { q: 'How can I track shipments?', a: 'Shipments can be created, monitored, and tracked through the IMS Transport module, providing real-time shipment visibility.' },
      { q: 'How is shipment verification performed?', a: 'Shipments are verified during both dispatch and receipt. Every verification event is automatically recorded in the audit log to ensure complete traceability.' },
    ],
  },
  {
    category: 'Traceability & Lots',
    icon: 'track_changes',
    items: [
      { q: 'What is product traceability?', a: 'The Trace feature enables you to track a product lot throughout its entire lifecycle, from production to final delivery, ensuring complete end-to-end traceability.' },
      { q: 'How can I trace a specific batch or lot?', a: 'Go to the Trace/Lots section, enter the Lot ID, and view the complete lifecycle of the batch, including its movement, storage locations, and transaction history.' },
      { q: 'How do I perform a product recall?', a: 'Using the traceability system, you can quickly identify affected lots and initiate a product recall. All recall activities are securely recorded in the audit log for compliance purposes.' },
      { q: 'What information is available in the Lot Dashboard?', a: "The Lot Dashboard provides a centralized view of each lot's inventory, movement history, warehouse location, and current status." },
    ],
  },
  {
    category: 'Billing & Subscription',
    icon: 'payments',
    items: [
      { q: 'Where can I find my billing information?', a: 'You can view your current subscription plan, invoices, payment history, and billing status from the Billing section of the Company Portal.' },
      { q: 'What subscription plans are available?', a: 'Khetify offers Basic and Premium subscription plans. Premium plans provide access to additional features and advanced functionality.' },
      { q: 'How can I upgrade or downgrade my subscription plan?', a: 'You can change your subscription plan at any time from the Billing section by selecting the desired plan.' },
      { q: 'Why is a premium feature locked?', a: 'The feature is not included in your current subscription plan. Upgrade to a Premium plan to gain access to premium features.' },
      { q: 'What should I do if my payment fails?', a: 'Verify your payment method and try the transaction again. If the problem persists, submit a support request under the Billing & Subscription category.' },
      { q: 'Can I download my invoices?', a: 'Yes. All generated invoices are available for download from the Billing section.' },
    ],
  },
  {
    category: 'Users, Roles, Compliance & Support',
    icon: 'manage_accounts',
    items: [
      { q: 'How do I assign roles to team members?', a: 'Navigate to the Users section, add a new team member, and assign an appropriate role such as Administrator, Staff, or Read-Only Auditor based on their responsibilities.' },
      { q: 'How can I get help if I encounter an issue?', a: 'If you need assistance, visit the Support Center and create a support request by selecting the appropriate category. Our support team typically responds within 4 business hours. Support Email: support@khetify.com. Support Hours: Monday to Saturday, 9:00 AM – 6:00 PM.' },
    ],
  },
];

export const SELLER_FAQ = [
  {
    category: 'Registration & Onboarding',
    icon: 'how_to_reg',
    items: [
      { q: 'Khetify par seller kaise ban sakta hoon?', a: 'Seller page par "Register as Seller" par click karke form bharein — naam, email, phone aur password dekar account create ho jata hai.' },
      { q: 'Seller register karne ke liye kya chahiye?', a: 'Shop/business name, contact details, address, GST/license (agar ho) aur bank/PAN details onboarding steps me maange jaate hain.' },
      { q: 'Seller banna free hai kya?', a: 'Account banana free hai; kuch advanced features plan/authorization par depend karte hain.' },
      { q: 'Registration ke baad kya karna hota hai?', a: 'Onboarding complete karein → profile bharein → jis company ka product bechna hai uske liye Principal Certificate (PC) apply karein.' },
      { q: 'Onboarding adhura chhoda to data save rahega?', a: 'Haan, aap wahi se continue kar sakte hain jahan chhoda tha.' },
      { q: 'Account turant chalu ho jata hai?', a: 'Account ban jata hai, par kisi company ke products bechne ke liye us company se PC issue hona zaroori hai.' },
    ],
  },
  {
    category: 'Login, Account & Security',
    icon: 'lock',
    items: [
      { q: 'Seller login kaise karun?', a: 'Seller Login page par registered email aur password se login karein.' },
      { q: 'Password bhool gaya to?', a: '"Forgot Password" par jaakar email par reset link mangwayein aur naya password set karein.' },
      { q: 'Password change kaha se hota hai?', a: 'Login karke Settings/Profile me jaakar password update karein.' },
      { q: 'Mera data secure hai?', a: 'Haan, encryption aur role-based access control se aapka account aur data protected rehta hai.' },
      { q: 'Login nahi ho raha, kya karun?', a: 'Email/password verify karein, reset try karein; phir bhi na chale to support se contact karein.' },
      { q: 'Ek se zyada log account use kar sakte hain?', a: 'Haan, Team section me members ko roles ke saath add kar sakte hain.' },
    ],
  },
  {
    category: 'Companies & Principal Certificate (PC)',
    icon: 'verified',
    items: [
      { q: 'Principal Certificate (PC) kya hota hai?', a: 'PC wo authorization hai jo ek company aapko deti hai taaki aap uske products officially bech sakein.' },
      { q: 'PC ke liye kaise apply karun?', a: 'Companies section me company search karke "Apply for PC" par click karein aur application form bharein.' },
      { q: 'Company kaise dhoondhun?', a: 'Companies page ke search box me company ka naam ya region daalein.' },
      { q: 'Recommended companies kya hoti hain?', a: 'Aapke profile/region ke hisaab se suggest ki gayi companies jinke liye aap PC apply kar sakte hain.' },
      { q: 'PC application ka status kaise pata chalega?', a: 'Companies/Certifications page par status dikhta hai — In progress, PC issued (active) ya Rejected.' },
      { q: '"PC issued" ka matlab kya hai?', a: 'Company ne aapko authorize kar diya — ab aap uske products bech sakte hain.' },
      { q: 'Meri PC application reject kyun hui?', a: 'Incomplete details, eligibility ya company ki policy ke hisaab se reject ho sakti hai; dobara apply kar sakte hain.' },
      { q: 'Ek saath kitni companies ke liye PC le sakta hoon?', a: 'Aap multiple companies ke liye apply/PC hold kar sakte hain.' },
      { q: 'Bina PC ke company ke products bech sakta hoon?', a: 'Nahi, kisi company ke products bechne ke liye us company ka PC hona zaroori hai.' },
      { q: 'Certifications page par kya hota hai?', a: 'Yahan aapki PC applications aur company-specific certification forms manage hote hain.' },
    ],
  },
  {
    category: 'Dashboard & Hub',
    icon: 'dashboard',
    items: [
      { q: 'Seller dashboard par kya dikhta hai?', a: 'Sales, orders, inventory, active companies (PC) aur performance ka overview.' },
      { q: 'Administration section me kya hota hai?', a: 'Team, Certifications, Billing, Customers aur Companies jaise account-level sections.' },
      { q: 'Data kitni jaldi update hota hai?', a: 'Real-time — orders aur stock changes turant reflect hote hain.' },
      { q: 'Mobile par bhi seller portal chalta hai?', a: 'Haan, portal responsive hai — mobile aur desktop dono par kaam karta hai.' },
    ],
  },
  {
    category: 'Product Catalog & Inventory',
    icon: 'inventory_2',
    items: [
      { q: 'Seller product catalog me kya hota hai?', a: 'Jin companies ka PC aapke paas hai, unke products aap catalog me manage/sell kar sakte hain.' },
      { q: 'Product apne aap add hote hain?', a: 'Company ke authorized products aapke liye available ho jaate hain; aap unhe apne stock ke saath manage karte hain.' },
      { q: 'Marketplace listings kya hain?', a: 'Wo products jo aapne Khetify storefront par publish kiye hain.' },
      { q: 'Seller inventory kaise manage hoti hai?', a: 'Inventory section me aapke products ka stock, batch aur availability track hoti hai.' },
      { q: 'Available stock kaise calculate hota hai?', a: 'availableStock = online + offline − reserved; sale/reservation par automatically adjust hota hai.' },
      { q: 'Batch aur expiry track hoti hai?', a: 'Haan, batch number aur expiry date ke saath stock control kar sakte hain.' },
      { q: 'Low-stock alert milega?', a: 'Haan, stock minimum level se neeche jaane par alert milta hai.' },
      { q: 'Stock movement history dekh sakta hoon?', a: 'Haan, har stock change ka append-only ledger maintain hota hai.' },
    ],
  },
  {
    category: 'Warehouses & Operations',
    icon: 'local_shipping',
    items: [
      { q: 'Warehouse kaise add karun?', a: 'Warehouses section me naam, location aur capacity dekar warehouse add karein.' },
      { q: 'Multiple warehouses rakh sakta hoon?', a: 'Haan, ek se zyada storage locations add kiye ja sakte hain.' },
      { q: 'Warehouse ke beech stock transfer ho sakta hai?', a: 'Haan, inter-warehouse transfer supported hai aur safely record hota hai.' },
      { q: 'Operations section me kya hota hai?', a: 'Inbound, outbound, transfers aur trace jaisi day-to-day stock activities.' },
      { q: 'Labels/barcodes print ho sakte hain?', a: 'Haan, Labels section se product/lot ke barcodes generate aur print kar sakte hain.' },
    ],
  },
  {
    category: 'Outbound, Supply & Customers',
    icon: 'local_mall',
    items: [
      { q: 'Outbound kya hota hai?', a: 'Outbound section me aap customers/dealers ko products dispatch/sell karte hain.' },
      { q: 'Order cancel ho to stock wapas aata hai?', a: 'Haan, cancellation par reserved stock release ho jata hai.' },
      { q: 'Delivery Khetify karta hai kya?', a: 'Nahi, delivery aap khud arrange karte hain — platform sirf order visibility deta hai.' },
      { q: 'Supply request kya hai?', a: 'Jab aapko company se stock chahiye, aap Supply section se replenishment request bhejte hain.' },
      { q: 'Supply request ka status kaise dekhun?', a: 'Supply page par request pending/approved/fulfilled status ke saath dikhti hai.' },
      { q: 'Customers section me kya hota hai?', a: 'Aapke buyers/farmers/dealers ki details, order history aur relationship management.' },
      { q: 'Customer ka credit/outstanding track hota hai?', a: 'Haan, customer-wise dues aur credit details manage kar sakte hain.' },
    ],
  },
  {
    category: 'Team, Analytics, Billing & Support',
    icon: 'payments',
    items: [
      { q: 'Team members kaise add karun?', a: 'Team section me member add karke role assign karein (admin/manager/staff).' },
      { q: 'Role-based access hai kya?', a: 'Haan, alag members ko alag permissions (jaise staff, auditor read-only) di ja sakti hain.' },
      { q: 'Analytics me kya milta hai?', a: 'Sales trends, top products, stock aging, expiry aur movement reports.' },
      { q: 'Billing me kya hota hai?', a: 'Aapka subscription plan aur usage; plan switch admin-only hota hai.' },
      { q: 'Khetify ki responsibility kya hai?', a: 'Khetify platform infrastructure, pricing visibility aur network access deta hai — delivery aur payment aap khud manage karte hain.' },
      { q: 'Koi issue ho to help kaise milegi?', a: 'Portal ke Support/Help option se request raise karein ya support par contact karein — issue detail ke saath likhein taaki jaldi solve ho.' },
    ],
  },
];
